# vim ft=yaml
sudo: required
dist: trusty
language: python

env:
  global:
    - DEPENDS="requirements.txt"

addons:
  apt:
    packages:
      - libatlas-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy

      
python:
  - "2.7"
  - "3.4"

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip install --upgrade pip
  - wheelhouse_pip_r_install ${DEPENDS}
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl;
    fi

install:
  - pip install -e .

script:
  - make travis-test

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
