# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="requirements.txt"

python:
  - 2.7

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip install --upgrade pip
  - wheelhouse_pip_r_install ${DEPENDS}
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

install:
  - pip install -e .

script:
  - make travis-test

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
